# Generated by Django 5.1.1 on 2024-09-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_prompt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textprompt',
            name='file',
        ),
        migrations.AddField(
            model_name='textprompt',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textprompt',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
