# Generated by Django 5.1.1 on 2024-09-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_prompt', '0004_alter_textprompt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileprompt',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
