# Generated by Django 5.1.1 on 2024-09-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_prompt', '0005_fileprompt_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textprompt',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
