# Generated by Django 5.1.1 on 2024-09-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_prompt', '0007_textprompt_format_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, max_length=300, null=True)),
                ('role', models.CharField(blank=True, max_length=300, null=True)),
                ('goal', models.CharField(blank=True, max_length=300, null=True)),
                ('restrictions', models.CharField(blank=True, max_length=300, null=True)),
                ('audience', models.CharField(blank=True, max_length=300, null=True)),
                ('format_result', models.CharField(blank=True, max_length=300, null=True)),
                ('writing_style', models.CharField(blank=True, max_length=300, null=True)),
                ('tone', models.CharField(blank=True, max_length=300, null=True)),
                ('keywords', models.CharField(blank=True, max_length=300, null=True)),
                ('examples', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='textprompt',
            old_name='response',
            new_name='question',
        ),
        migrations.DeleteModel(
            name='FilePrompt',
        ),
    ]
