# Generated by Django 5.1.1 on 2024-09-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(related_name='user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='permissions',
            field=models.ManyToManyField(related_name='user_permissions', to='auth.permission'),
        ),
    ]
