# Generated by Django 5.1.1 on 2024-09-17 11:58

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_groups_alter_customuser_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', authentication.models.CustomManager()),
            ],
        ),
    ]
